<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Amount' => 'Bedrag',
    'Cancel Dummy Payment' => 'Annuleer dummy-betaling',
    'Cancelled' => 'Afgebroken',
    'Complete Dummy Payment' => 'Voltooi dummy-betaling',
    'Donate' => 'Doneer',
    'Donate €' => 'Doneer €',
    'Donate!' => 'Doneer!',
    'Donated At' => 'Gedoneerd op',
    'Donation for {site}' => 'Donatie voor {site}',
    'Donations' => 'Donaties',
    'Dummy Payment' => 'Dummy-betaling',
    'Email' => 'E-mail',
    'Hello {username},' => 'Hallo {username},',
    'Keep up the good work!' => 'Zet het goede werk voort!',
    'Many thanks for your donation!' => 'Veel dank voor je donatie',
    'Message' => 'Bericht',
    'Mollie payment ID' => 'Mollie payment ID',
    'Page' => 'Pagina',
    'Please, select an amount...' => 'Kies een bedrag...',
    'Resume' => 'Ga verder',
    'Say something friendly' => 'Zeg iets aardigs',
    'Send an email' => 'Stuur een e-mail',
    'Status' => 'Status',
    'Thank you for your {amount} donation of {date}.' => 'Bedankt voor je donatie van {amount} op {date}.',
    'Thanks' => 'Bedankt',
    'The requested donation does not exist.' => 'De opgevraagde donatie bestaat niet.',
    'This is a dummy payment for testing purposes only. No money is transferred' => 'Dit is een dummy-betaling bij wijze van test. Er wordt geen geld overgemaakt.',
    'Total:' => 'Totaal:',
    'Your donation has been cancelled. No money is transferred.' => 'Je donatie is afgebroken. Er is geen geld overgemaakt.',
    'donor@example.com (optional)' => 'donor@example.com (optioneel)',
];
